### ISSUE TITLE
Support `text` parameter

### ISSUE THREAD

**Issue by vpicone** [SirPole/google-fonts-plugin#11]
Sometimes you just need a single character, google allows you to do so with the text parameter

`@import url('https://fonts.googleapis.com/css?family=IBM+Plex+Sans&text=↳');`

It would be awesome if this was an option in addition to subset and the like

**Comment by SirPole** [comment]
Hey! This issue is now resolved in version **[5.0.0](https://www.npmjs.com/package/google-fonts-plugin)**! 🚀 See [release notes](https://github.com/SirPole/google-fonts-plugin/releases/tag/v5.0.0) and [readme](https://github.com/SirPole/google-fonts-plugin#readme) for more information.
