### ISSUE TITLE
The manifest generated for the 'google-fonts' chunk points to an invalid JS file

### ISSUE THREAD

**Issue by commonbreed** [SirPole/google-fonts-plugin#13]
My configuration pushes the following files to the public/directory:
- woff.css
- woff2.css

The manifest file generated contains the following links:
"google-fonts.js": "/1.main.js",
"google-fonts.css": "/woff2.css",

So my query is, why does the plugin only reference the woff2 version in the manifest, and where is this 1.main.js file coming from? It certainly doesn't exist in the filesystem, and trying to interpret it as an entry point just reports "File not found".

**Comment by SirPole** [comment]
Hey! I'm sorry you're having issues. Can you please provide example configuration and packages that leads to your issue?

**Comment by SirPole** [comment]
Hey! This issue **should** now be resolved in version **[5.0.0](https://www.npmjs.com/package/google-fonts-plugin)**! 🚀 See [release notes](https://github.com/SirPole/google-fonts-plugin/releases/tag/v5.0.0) and [readme](https://github.com/SirPole/google-fonts-plugin#readme) for more information.
