### ISSUE TITLE
Add an option to save the file as .scss to import it into scss

### ISSUE THREAD

**Issue by sxzctzppyw** [SirPole/google-fonts-plugin#16]
Hi,
It is possible to add an option to save the file as .scss to import it into scss?

**Comment by SirPole** [comment]
Hello, sorry for late reply, I'm currently working on rewriting the plugin. There will be an option to specify whatever custom filename you want... Stay tuned!

**Comment by jpic** [comment]
Good to know, fantastic plugin.

**Comment by SirPole** [comment]
Hey! This issue is now resolved in version **[5.0.0](https://www.npmjs.com/package/google-fonts-plugin)**! 🚀 See [release notes](https://github.com/SirPole/google-fonts-plugin/releases/tag/v5.0.0) and [readme](https://github.com/SirPole/google-fonts-plugin#readme) for more information.
