### ISSUE TITLE
Version 5: TypeError: GoogleFontsPlugin is not a constructor

### ISSUE THREAD

**Issue by minotogna** [SirPole/google-fonts-plugin#17]
Hello,

I have migrated to version 5 of the plugin and I get the error:
`TypeError: GoogleFontsPlugin is not a constructor`
Is the usage changed?

Thank you,
Mino

**Comment by SirPole** [comment]
Hello, version 5 should have been a prerelease for testing purposes (which failed, as you can see 😄). I'm hoping to release 5.0.0 today!
