### ISSUE TITLE
Add Content-Security-Policy support

### ISSUE THREAD

**Issue by jimmyandrade** [SirPole/google-fonts-plugin#18]
I have `gatsby-plugin-csp` configured on my Gatsby website project. As `google-fonts-plugin` does not generate a sha256 or nonce for the style, I found the following error on my console:

```
Refused to apply inline style because it violates the following Content Security Policy directive:
"style-src 'self' 'unsafe-inline' 'sha256-Pdo3pCbzuSlukPymsHhzPWJbg+ZN57Ij22Y/tykPrNc='"
Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.
```

Just adding `'self' 'unsafe-inline'` to `style-src` header is not enough.

**Expected**
Add some `nonce` or `sha256` attribute to `<style>`

**Additional context**
- [Content Security Policy on Google Developers](https://developers.google.com/web/fundamentals/security/csp/)
- [style-src on Content-Security-Policy header on Mozilla Developer](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src)

**Comment by SirPole** [comment]
Hello, the plugin simply generates css files, how you handle and serve these is completely up to you.

I however found this stub in gatsby-plugin-csp page
```
sha256 for every inline script and style is generated automatically during the build process and appended to its directive (script-src or style-src).
```
It seems to me that it should create the hashes itself... :X I haven't yet had much experience with gatsby (just started a personal project!), so I might be wrong on this :) 

If you believe this is something with the plugin, I would appreciate a reproducible configuration example or at least an example of another plugin that does it right.
