### ISSUE TITLE
This plugin has stopped working

### ISSUE THREAD

**Issue by sc-searchengineunity** [SirPole/google-fonts-plugin#31]
It was working fine this morning and went down a few hours ago. Once I have cleared by Gatsby .cache via Gatsby clean, it was unable to recreate local copies to be prefetched.

**Comment by vizath** [comment]
Same here using `gatsby-plugin-prefetch-google-fonts` (https://www.gatsbyjs.com/plugins/gatsby-plugin-prefetch-google-fonts/).

Note that `gatsby-plugin-prefetch-google-fonts` is using version `2.0.2`: https://github.com/escaladesports/legacy-gatsby-plugin-prefetch-google-fonts/blob/master/package.json#L85

*Edit:*
It looks like an issue with gatsby's plugin.
My assumption is that Google Font changed their way of serving files, which breaks the plugin parsing mechanism:
https://github.com/escaladesports/legacy-gatsby-plugin-prefetch-google-fonts/blob/master/plugins/export/merge-css.js#L31

I ended up dropping the plugin and importing Google Font directly in CSS.

**Comment by sc-searchengineunity** [comment]
I did the same. I think Google Fonts dropped local() as per one of their recent twitter.
