### ISSUE TITLE
Breaking Change: outputDir option was removed with 2.1.0

### ISSUE THREAD

**Issue by sapkra** [SirPole/google-fonts-plugin#7]
I tried running the following plugin which is using your plugin as a dependency. Since you've released version `2.1.0` the entire plugin is broken. It is using the `outputDir` option which was removed in version `2.1.0`.

Please don't release minor version with breaking changes. It has to be a new major version like `3.0.0`.
You also forgot to document this change in the changelog so I had to reverse engineer both plugins to figure out what's the problem.

The related issue:
https://github.com/escaladesports/gatsby-plugin-prefetch-google-fonts/issues/8

**Comment by SirPole** [comment]
Hey! That's definitely my error, I've marked 2.1.0 as deprecated in npm and released 3.0.0. 

I'm sorry for any inconvenience caused by this.

**Comment by sapkra** [comment]
Thanks you for your fast response and of cause the PR. ❤️
Very often it takes a lot of time until the maintainer is reacting on issues.
